# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  paths:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script:
    npm install
  displayName: 'Install dependecies'  

- script:
    npm run cy:verify
  displayName: 'Cypress verify'

- script:
    npm run cy:run-junit-reporter
  continueOnError: true
  displayName: 'Execute cypress tests' 

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Cypress tests'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      function Send-SlackMessage {
          param (
              [Parameter(Mandatory=$true, Position=0)]$Text,
              [Parameter(Mandatory=$true, Position=1)]$Url
          )
          $body= @"
          {
              "username": "Test reporter",
              "text": "MESSAGE_TEXT",
              "icon_emoji":":scroll:"
          }
      "@
      
          Invoke-WebRequest -Method Post -Uri $Url -Body $body.Replace("MESSAGE_TEXT","$Text") -ContentType 'application/json'
      }
      Write-Host "Sending slack message for BUILD: $($env:BUILD_BUILDID)"
      
      $nl = "`r`n`r`n"
      $dnl = "`r`n`r`n `r`n`r`n"
      
      Send-SlackMessage "<!channel> $nl Automation Project Test Results $dnl BuildId: $($env:BUILD_BUILDID) $dnl Test results: https://dev.azure.com/marcinstanekpl/Conduit%20e2e%20tests/_build/results?buildId=$($env:BUILD_BUILDID)&view=ms.vss-test-web.build-test-results-tab $dnl Test analitycs: https://dev.azure.com/marcinstanekpl/Conduit%20e2e%20tests/_test/analytics?definitionId=1&contextType=build" $($env:WEBHOOK_URL)