# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  paths:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    export CYPRESS_BASE_URL=https://conduit-ef845.web.app
    export CYPRESS_APIURL=https://conduit-backend.herokuapp.com
    npx cypress run
  displayName: 'npm install and execute cypress tests'
